var S = require('./engine.js');
var pass = 0, fail = 0;
function t(name, got, want) {
  var ok = JSON.stringify(got) === JSON.stringify(want);
  if (ok) pass++; else { fail++; console.log('FAIL ' + name + ': got ' + JSON.stringify(got) + ' want ' + JSON.stringify(want)); }
}
t('amps from watts', S.ampsFromWatts(1500, 120), 12.5);
t('amps from watts 240', S.ampsFromWatts(7680, 240), 32);
t('amps zero volts safe', S.ampsFromWatts(100, 0), 0);
t('drop saw 16awg', S.voltageDrop(15, 100, '16'), 12.27);
t('drop saw 12awg', S.voltageDrop(15, 100, '12'), 4.86);
t('drop saw 10awg', S.voltageDrop(15, 100, '10'), 3.06);
t('drop unknown gauge null', S.voltageDrop(15, 100, '18'), null);
t('pct saw 16', S.dropPct(12.27, 120), 10.23);
t('pct saw 12', S.dropPct(4.86, 120), 4.05);
t('pct saw 10', S.dropPct(3.06, 120), 2.55);
t('heat saw 16', S.heatWatts(15, 100, '16'), 184.05);
t('maxlen 15A 120V 12awg', S.maxLenFt(15, 120, '12'), 74);
t('maxlen zero amps', S.maxLenFt(0, 120, '12'), 0);
t('level 2.55 good', S.levelFor(2.55), 'good');
t('level 4.05 warn', S.levelFor(4.05), 'warn');
t('level 10.23 bad', S.levelFor(10.23), 'bad');
t('level boundary 3 good', S.levelFor(3), 'good');
t('level boundary 5 warn', S.levelFor(5), 'warn');
var saw = S.compute({ amps: 15, volts: 120, lengthFt: 100, awg: '16' });
t('saw drop', saw.vDrop, 12.27);
t('saw pct', saw.pct, 10.23);
t('saw end volts', saw.atEndVolts, 107.73);
t('saw table 6 rows', saw.table.length, 6);
t('saw table 16 bad', saw.table[0].level, 'bad');
t('saw table 10 good', saw.table[3].level, 'good');
t('saw ampacity bad', saw.checks.some(function (c) { return c.level === 'bad' && c.text.indexOf('13 A ampacity') > -1; }), true);
t('saw drop bad', saw.checks.some(function (c) { return c.level === 'bad' && c.text.indexOf('5% combined') > -1; }), true);
t('saw heat warn', saw.checks.some(function (c) { return c.level === 'warn' && c.text.indexOf('coiled') > -1; }), true);
var ev = S.compute({ amps: 32, volts: 240, lengthFt: 40, awg: '8', continuous: true });
t('ev pct', ev.pct, 0.68);
t('ev continuous boundary ok', ev.checks.some(function (c) { return c.level === 'good' && c.text.indexOf('40 A ampacity') > -1; }), true);
var ev6 = S.compute({ amps: 32, volts: 240, lengthFt: 40, awg: '8', continuous: true, ampsOverride: null });
var cont = S.compute({ amps: 34, volts: 240, lengthFt: 20, awg: '8', continuous: true });
t('continuous 125 warn', cont.checks.some(function (c) { return c.level === 'warn' && c.text.indexOf('125%') > -1; }), true);
var over = S.compute({ amps: 20, volts: 120, lengthFt: 10, awg: '14' });
t('over ampacity bad', over.checks.some(function (c) { return c.level === 'bad' && c.text.indexOf('fuse now') > -1; }), true);
var welder = S.compute({ amps: 30, volts: 240, lengthFt: 60, awg: '10' });
t('welder pct', welder.pct, 1.53);
var watts = S.compute({ watts: 1500, volts: 120, lengthFt: 50, awg: '14' });
t('watts mode amps', watts.amps, 12.5);
t('watts drop', watts.vDrop, 3.23);
t('rejects no gauge', S.compute({ amps: 5, volts: 120, lengthFt: 10, awg: '18' }).error.length > 0, true);
t('rejects zero length', S.compute({ amps: 5, volts: 120, lengthFt: 0, awg: '12' }).error.length > 0, true);
console.log(pass + '/' + (pass + fail) + ' tests passed');
process.exit(fail ? 1 : 0);
